export {
  ALLOWED_DOCUMENT_MIME_TYPES,
  ALLOWED_IMAGE_MIME_TYPES,
  MAX_DOCUMENT_SIZE_BYTES,
  MAX_IMAGE_SIZE_BYTES,
  candidateCvFileSchema,
  candidateSubmissionSchema,
  isDocumentMimeType,
  isImageMimeType,
  projectAttachmentSchema,
  projectSubmissionSchema,
  submissionCreateSchema,
  type CandidateSubmissionInput,
  type ProjectSubmissionInput,
  type SubmissionCreateInput,
  type UploadedFileInput,
} from '@/shared/validation/submissions';
